{"id": "af44091c-01b5-4b6c-9650-e29c9e1c7e5a", "agents": [{"number": 0, "data": {}, "history": "{\"_cls\": \"History\", \"bulks\": [], \"topics\": [{\"_cls\": \"Topic\", \"summary\": \"\", \"messages\": [{\"_cls\": \"Message\", \"ai\": false, \"content\": {\"user_message\": \"hi\"}, \"summary\": \"\"}]}, {\"_cls\": \"Topic\", \"summary\": \"\", \"messages\": [{\"_cls\": \"Message\", \"ai\": false, \"content\": {\"user_message\": \"hi\"}, \"summary\": \"\"}]}], \"current\": {\"_cls\": \"Topic\", \"summary\": \"\", \"messages\": [{\"_cls\": \"Message\", \"ai\": false, \"content\": {\"user_message\": \"hi\"}, \"summary\": \"\"}]}}"}], "streaming_agent": 0, "log": {"guid": "13bf642e-783f-487b-a0e2-2df8ca9f1b78", "logs": [{"no": 0, "id": null, "type": "user", "heading": "User message", "content": "hi", "temp": false, "kvps": {"attachments": []}}, {"no": 1, "id": null, "type": "info", "heading": "", "content": "Searching memories...", "temp": true, "kvps": null}, {"no": 2, "id": null, "type": "util", "heading": "Searching memories...", "content": "", "temp": false, "kvps": {"query": "user hi\n"}}, {"no": 3, "id": null, "type": "info", "heading": "", "content": "Searching memory for solutions...", "temp": true, "kvps": null}, {"no": 4, "id": null, "type": "util", "heading": "Searching memory for solutions...", "content": "", "temp": false, "kvps": {"query": "USER: I want to convert a png image to a jpeg image\nAI: convert png to jpeg\n"}}, {"no": 5, "id": null, "type": "util", "heading": "Initializing VectorDB in '/default'", "content": "", "temp": false, "kvps": {"progress": "\nInitializing VectorDB"}}, {"no": 6, "id": null, "type": "error", "heading": "Error", "content": "Traceback (most recent call last):\nTraceback (most recent call last):\n  File \"/a0/agent.py\", line 265, in monologue\n    prompt = await self.prepare_prompt(loop_data=self.loop_data)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/a0/agent.py\", line 349, in prepare_prompt\n    await self.call_extensions(\"message_loop_prompts\", loop_data=loop_data)\n  File \"/a0/agent.py\", line 679, in call_extensions\n    await cls(agent=self).execute(**kwargs)\n  File \"/a0/python/extensions/message_loop_prompts/_91_recall_wait.py\", line 13, in execute\n    await task\n  File \"/a0/python/extensions/message_loop_prompts/_50_recall_memories.py\", line 67, in search_memories\n    db = await Memory.get(self.agent)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n>>>  5 stack lines skipped <<<\n\n  File \"/opt/venv/lib/python3.11/site-packages/langchain_openai/embeddings/base.py\", line 588, in embed_documents\n    return self._get_len_safe_embeddings(texts, engine=engine)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/venv/lib/python3.11/site-packages/langchain_openai/embeddings/base.py\", line 483, in _get_len_safe_embeddings\n    response = self.client.create(\n               ^^^^^^^^^^^^^^^^^^^\n  File \"/opt/venv/lib/python3.11/site-packages/openai/resources/embeddings.py\", line 128, in create\n    return self._post(\n           ^^^^^^^^^^^\n  File \"/opt/venv/lib/python3.11/site-packages/openai/_base_client.py\", line 1242, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/venv/lib/python3.11/site-packages/openai/_base_client.py\", line 919, in request\n    return self._request(\n           ^^^^^^^^^^^^^^\n  File \"/opt/venv/lib/python3.11/site-packages/openai/_base_client.py\", line 1023, in _request\n    raise self._make_status_error_from_response(err.response) from None\nopenai.AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-FiIu6*************hogQ. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}\n", "temp": false, "kvps": {"text": "Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-FiIu6*************hogQ. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}"}}, {"no": 7, "id": null, "type": "info", "heading": "", "content": "Memorizing new information...", "temp": true, "kvps": null}, {"no": 8, "id": null, "type": "util", "heading": "No useful information to memorize.", "content": "[]\n", "temp": false, "kvps": null}, {"no": 9, "id": null, "type": "info", "heading": "", "content": "Memorizing succesful solutions...", "temp": true, "kvps": null}, {"no": 10, "id": null, "type": "util", "heading": "No successful solutions to memorize.", "content": "[]\n", "temp": false, "kvps": null}, {"no": 11, "id": null, "type": "util", "heading": "Initializing VectorDB in '/default'", "content": "", "temp": false, "kvps": {"progress": "\nInitializing VectorDB"}}, {"no": 12, "id": null, "type": "user", "heading": "User message", "content": "hi", "temp": false, "kvps": {"attachments": []}}, {"no": 13, "id": null, "type": "info", "heading": "", "content": "Searching memories...", "temp": true, "kvps": null}, {"no": 14, "id": null, "type": "util", "heading": "Searching memories...", "content": "", "temp": false, "kvps": {"query": "user hi\n"}}, {"no": 15, "id": null, "type": "info", "heading": "", "content": "Searching memory for solutions...", "temp": true, "kvps": null}, {"no": 16, "id": null, "type": "util", "heading": "Searching memory for solutions...", "content": "", "temp": false, "kvps": {"query": "USER: I want to convert a png image to a jpeg image\nAI: convert png to jpeg\n"}}, {"no": 17, "id": null, "type": "util", "heading": "Initializing VectorDB in '/default'", "content": "", "temp": false, "kvps": {"progress": "\nInitializing VectorDB"}}, {"no": 18, "id": null, "type": "error", "heading": "Error", "content": "Traceback (most recent call last):\nTraceback (most recent call last):\n  File \"/a0/agent.py\", line 265, in monologue\n    prompt = await self.prepare_prompt(loop_data=self.loop_data)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/a0/agent.py\", line 349, in prepare_prompt\n    await self.call_extensions(\"message_loop_prompts\", loop_data=loop_data)\n  File \"/a0/agent.py\", line 679, in call_extensions\n    await cls(agent=self).execute(**kwargs)\n  File \"/a0/python/extensions/message_loop_prompts/_91_recall_wait.py\", line 13, in execute\n    await task\n  File \"/a0/python/extensions/message_loop_prompts/_50_recall_memories.py\", line 67, in search_memories\n    db = await Memory.get(self.agent)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n>>>  5 stack lines skipped <<<\n\n  File \"/opt/venv/lib/python3.11/site-packages/langchain_openai/embeddings/base.py\", line 588, in embed_documents\n    return self._get_len_safe_embeddings(texts, engine=engine)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/venv/lib/python3.11/site-packages/langchain_openai/embeddings/base.py\", line 483, in _get_len_safe_embeddings\n    response = self.client.create(\n               ^^^^^^^^^^^^^^^^^^^\n  File \"/opt/venv/lib/python3.11/site-packages/openai/resources/embeddings.py\", line 128, in create\n    return self._post(\n           ^^^^^^^^^^^\n  File \"/opt/venv/lib/python3.11/site-packages/openai/_base_client.py\", line 1242, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/venv/lib/python3.11/site-packages/openai/_base_client.py\", line 919, in request\n    return self._request(\n           ^^^^^^^^^^^^^^\n  File \"/opt/venv/lib/python3.11/site-packages/openai/_base_client.py\", line 1023, in _request\n    raise self._make_status_error_from_response(err.response) from None\nopenai.AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-FiIu6*************hogQ. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}\n", "temp": false, "kvps": {"text": "Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-FiIu6*************hogQ. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}"}}, {"no": 19, "id": "1ca3b9ed-6861-4af1-a2d3-26758a85f953", "type": "user", "heading": "User message", "content": "hi", "temp": false, "kvps": {"attachments": []}}, {"no": 20, "id": null, "type": "info", "heading": "", "content": "Searching memories...", "temp": true, "kvps": {}}, {"no": 21, "id": null, "type": "util", "heading": "Searching memories...", "content": "", "temp": false, "kvps": {"query": "user hi\n"}}, {"no": 22, "id": null, "type": "info", "heading": "", "content": "Searching memory for solutions...", "temp": true, "kvps": {}}, {"no": 23, "id": null, "type": "util", "heading": "Searching memory for solutions...", "content": "", "temp": false, "kvps": {}}, {"no": 24, "id": null, "type": "util", "heading": "Initializing VectorDB in '/default'", "content": "", "temp": false, "kvps": {"progress": "\nInitializing VectorDB"}}, {"no": 25, "id": null, "type": "error", "heading": "Error", "content": "Traceback (most recent call last):\nTraceback (most recent call last):\n  File \"/a0/agent.py\", line 265, in monologue\n    prompt = await self.prepare_prompt(loop_data=self.loop_data)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/a0/agent.py\", line 349, in prepare_prompt\n    await self.call_extensions(\"message_loop_prompts\", loop_data=loop_data)\n  File \"/a0/agent.py\", line 679, in call_extensions\n    await cls(agent=self).execute(**kwargs)\n  File \"/a0/python/extensions/message_loop_prompts/_91_recall_wait.py\", line 13, in execute\n    await task\n  File \"/a0/python/extensions/message_loop_prompts/_50_recall_memories.py\", line 67, in search_memories\n    db = await Memory.get(self.agent)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n>>>  5 stack lines skipped <<<\n\n  File \"/opt/venv/lib/python3.11/site-packages/langchain_openai/embeddings/base.py\", line 588, in embed_documents\n    return self._get_len_safe_embeddings(texts, engine=engine)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/venv/lib/python3.11/site-packages/langchain_openai/embeddings/base.py\", line 483, in _get_len_safe_embeddings\n    response = self.client.create(\n               ^^^^^^^^^^^^^^^^^^^\n  File \"/opt/venv/lib/python3.11/site-packages/openai/resources/embeddings.py\", line 128, in create\n    return self._post(\n           ^^^^^^^^^^^\n  File \"/opt/venv/lib/python3.11/site-packages/openai/_base_client.py\", line 1242, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/venv/lib/python3.11/site-packages/openai/_base_client.py\", line 919, in request\n    return self._request(\n           ^^^^^^^^^^^^^^\n  File \"/opt/venv/lib/python3.11/site-packages/openai/_base_client.py\", line 1023, in _request\n    raise self._make_status_error_from_response(err.response) from None\nopenai.AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-FiIu6*************hogQ. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}\n", "temp": false, "kvps": {"text": "Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-FiIu6*************hogQ. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}"}}], "progress": "Error", "progress_no": 25}}